credentians:
    url: https://gitlab.com/
    private_token:
    api_version: v4
    assignee_id: 

jobs_mr:
    - project:
        path: caulax/haproxy
        title: TEST
        source_branch: develop
        target_branch: master
        labels: test
