credentians:
    url: https://gitlab.ivaldi.norse.digital/
    private_token: mbFzB-bwj_yAZcQebjtq
    api_version: v4
    assignee_id: 36

jobs_mr:
    - project:
        path: vits/interaction-apis
        title: BACKEND develop to develop_copy_tmp
        source_branch: develop
        target_branch: develop_copy_tmp
        labels: release1
